In [3]:
a = int(input())
def fact(x):
    if x == 0:
        return 1
    else:
        return fact(x-1)*x
print(fact(a))

5
120


In [14]:
y = int(input())
if y % 4 != 0 or (y % 100 == 0 and y % 400 != 0):
    print(0)
else:
    print(1)

2000
1


In [10]:
import numpy as np
k = np.array([2, 3, 4, 1, 0])
n = int(input())
def zeros_insert(k,n):
    new = list()
    for i in k:
        new.append(float(i))
        for i in range(n):
            new.append(0.)
    for i in range(n):
        new.pop()
    new = np.array(new)    
    return new        
r = zeros_insert(k, n)
print(r)

8
[2. 0. 0. 0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 4. 0. 0. 0. 0. 0.
 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
import pandas as pd
s = pd.Series([1,3,2])
def peak_finder(s):
    result = []
    for i in s.index:
        if i>0 and i<max(s.index):
            if s[i]>s[i-1] and s[i]>s[i+1]:
                result.append(i) 
    result = np.array(result)            
    return result            
r = peak_finder(s)
print(r)

[1]


In [59]:
import pandas as pd
df = [[16,  5, 23,  4, 20],
      [24,  8, 15, 24,  9],
      [15, 11,  9,  8,  7],
      [ 5, 17,  8, 13,  1],
      [12, 24,  7, 20, 13]]
df = pd.DataFrame(df)
def df_diag_ones(data):
    N,M = data.shape
    for i in range(N):
        for j in range(M):
            if i == j or (i+j)==N-1:
                data[i][j]=1
    return data        
df = df_diag_ones(df)
print(df.values)

[[ 1  5 23  4  1]
 [24  1 15  1  9]
 [15 11  1  8  7]
 [ 5  1  8  1  1]
 [ 1 24  7 20  1]]
